
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"

conda:
    environment: docs/environment.yaml
        
# By default readthedocs does not checkout git submodules
submodules:                                                                                                                          
    include: all
    
# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

